name: sens-calc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - astropy=5.3
  - numpy=1.26
  - pytest=7.2
  - pytest-mock=3.10
  - PyYAML=6.0
  - scipy=1.11
  - setuptools=65.5
  - sphinx_rtd_theme=1.1
  - nbsphinx==0.8
  - python-dotenv=0.21
  - pydantic=1.10
  - pandoc
  - build
  - flake8
  - sphinx-copybutton
  - fastapi=0.94
  - uvicorn=0.21
  - jinja2=3.1
  - aiofiles=22.1
  - coverage=7.2
  - pylint
  - pip
  - httpx=0.24
  - pip:
      - sphinxcontrib.plantuml==0.25
      - -e ./
